INSERT INTO USERS VALUES (1, SYSDATE, FALSE, SYSDATE, 0, 'customer', 'CUSTOMER');
INSERT INTO USERS VALUES (2, SYSDATE, FALSE, SYSDATE, 0, 'admin', 'ADMIN');

INSERT INTO PRODUCT VALUES (1, SYSDATE, FALSE, SYSDATE, 0, 4, 'Black Coffee', 'DRINK');
INSERT INTO PRODUCT VALUES (2, SYSDATE, FALSE, SYSDATE, 0, 5, 'Latte', 'DRINK');
INSERT INTO PRODUCT VALUES (3, SYSDATE, FALSE, SYSDATE, 0, 6, 'Mocha','DRINK');
INSERT INTO PRODUCT VALUES (4, SYSDATE, FALSE, SYSDATE, 0, 3, 'Tea', 'DRINK');

INSERT INTO PRODUCT VALUES (5, SYSDATE, FALSE, SYSDATE, 0, 2, 'Milk', 'SIDE');
INSERT INTO PRODUCT VALUES (6, SYSDATE, FALSE, SYSDATE, 0, 3, 'Hazelnut syrup', 'SIDE');
INSERT INTO PRODUCT VALUES (7, SYSDATE, FALSE, SYSDATE, 0, 5, 'Chocolate sauce', 'SIDE');
INSERT INTO PRODUCT VALUES (8, SYSDATE, FALSE, SYSDATE, 0, 2, 'Lemon', 'SIDE');